LOVE = []

HUG = []

PET = [
    "CgACAgQAAxkBAAIBnWkBt0XaLrcoK4-B2sxR5ySG1B6kAAIOAwACuAYNU_Yqj588XXEzNgQ",
    "CgACAgQAAxkBAAIBn2kBt0exCfMYAAGCtge8juz2o_Ch2AACKAMAAtzIDVMJmuxlq1r_ZDYE",
    "CgACAgQAAxkBAAIBoWkBt0tbYCGFHX1dgJDsJZXtMysvAAK2BgACQ2ocUri_O7_8fuKvNgQ",
    "CgACAgQAAxkBAAIBo2kBt06sthmrAnqXK_jlINSzxF4LAAKHBgACVNuMUG2_K9SXCbgZNgQ",
]

SLAP = [
    "CgACAgQAAxkBAAIB3WkBvfOH6Xh0E6rH_DFQ2oXKSjACAAL2AwACGIiUUqrLEDx7AUBVNgQ",
    "CgACAgQAAxkBAAIB32kBvfXsvzNerpWokHQFK5ouKtLQAAJWAwACx6kFU__XvGkGjPsGNgQ",
    "CgACAgQAAxkBAAIBy2kBvbtjcT5uudPn8zT4RF6_T3g9AAIEBgACTw9tUxph-KuOtYTINgQ",
    "CgACAgQAAxkBAAIBzWkBvbzLO5hqDYRnUCMdCv-lZGuzAALqBQACrW7UULbDynF-sbhENgQ",
    "CgACAgQAAxkBAAIBx2kBvbiK1e_AF1U4nN7U_70GHSBfAAJeBQACk058UY8kuP8E0gABeDYE",
]
